// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYh6CY0rHzSYhhUgcrH5XVt_txjXvnor4',
    appId: '1:1049276875265:android:a0a1f2205b7ad1d93db600',
    messagingSenderId: '1049276875265',
    projectId: 'thebasic-bff08',
    databaseURL: 'https://thebasic-bff08-default-rtdb.firebaseio.com',
    storageBucket: 'thebasic-bff08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClnqq85kptOUE6ZU8fdiUQ7szBIPleySo',
    appId: '1:1049276875265:ios:cc12af70de8f5a2c3db600',
    messagingSenderId: '1049276875265',
    projectId: 'thebasic-bff08',
    databaseURL: 'https://thebasic-bff08-default-rtdb.firebaseio.com',
    storageBucket: 'thebasic-bff08.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager',
  );
}
